// <editor-fold defaultstate="collapsed" desc="GNU General Public License">
//
//   SynchroScore
//   Copyright (C) 2009 Shayne Hughes
//
//   This program is free software: you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation, either version 3 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.
//
//   You should have received a copy of the GNU General Public License
//   along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
// </editor-fold>
package org.aquastarz.score.gui;

import java.util.Collection;
import java.util.List;
import org.aquastarz.score.domain.Figure;
import org.aquastarz.score.domain.FigureScore;

public class FigureScorePanel extends javax.swing.JPanel {

    /** Creates new form FigureScorePanel */
    public FigureScorePanel() {
        initComponents();
        setEditableRow(0);
    }

    public void setData(List<Figure> figures, Collection<FigureScore> figureScores) {
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        stationSelected = new javax.swing.ButtonGroup();
        station1Button = new javax.swing.JRadioButton();
        station2Button = new javax.swing.JRadioButton();
        station3Button = new javax.swing.JRadioButton();
        station4Button = new javax.swing.JRadioButton();
        scoreS1J1 = new javax.swing.JTextField();
        scoreS1J2 = new javax.swing.JTextField();
        scoreS1J3 = new javax.swing.JTextField();
        scoreS1J4 = new javax.swing.JTextField();
        scoreS1J5 = new javax.swing.JTextField();
        penalty2S1 = new javax.swing.JCheckBox();
        penalty1S1 = new javax.swing.JCheckBox();
        penaltyHS1 = new javax.swing.JCheckBox();
        raw1 = new javax.swing.JLabel();
        dd1 = new javax.swing.JLabel();
        total1 = new javax.swing.JLabel();
        fig1 = new javax.swing.JLabel();
        pen1 = new javax.swing.JLabel();
        scoreS2J1 = new javax.swing.JTextField();
        scoreS2J2 = new javax.swing.JTextField();
        scoreS2J3 = new javax.swing.JTextField();
        scoreS2J4 = new javax.swing.JTextField();
        scoreS2J5 = new javax.swing.JTextField();
        penalty2S2 = new javax.swing.JCheckBox();
        penalty1S2 = new javax.swing.JCheckBox();
        penaltyHS2 = new javax.swing.JCheckBox();
        raw2 = new javax.swing.JLabel();
        dd2 = new javax.swing.JLabel();
        total2 = new javax.swing.JLabel();
        fig2 = new javax.swing.JLabel();
        pen2 = new javax.swing.JLabel();
        scoreS3J1 = new javax.swing.JTextField();
        scoreS3J2 = new javax.swing.JTextField();
        scoreS3J3 = new javax.swing.JTextField();
        scoreS3J4 = new javax.swing.JTextField();
        scoreS3J5 = new javax.swing.JTextField();
        penalty2S3 = new javax.swing.JCheckBox();
        penalty1S3 = new javax.swing.JCheckBox();
        penaltyHS3 = new javax.swing.JCheckBox();
        raw3 = new javax.swing.JLabel();
        dd3 = new javax.swing.JLabel();
        total3 = new javax.swing.JLabel();
        fig3 = new javax.swing.JLabel();
        pen3 = new javax.swing.JLabel();
        scoreS4J1 = new javax.swing.JTextField();
        scoreS4J2 = new javax.swing.JTextField();
        scoreS4J3 = new javax.swing.JTextField();
        scoreS4J4 = new javax.swing.JTextField();
        scoreS4J5 = new javax.swing.JTextField();
        penalty2S4 = new javax.swing.JCheckBox();
        penalty1S4 = new javax.swing.JCheckBox();
        penaltyHS4 = new javax.swing.JCheckBox();
        raw4 = new javax.swing.JLabel();
        dd4 = new javax.swing.JLabel();
        total4 = new javax.swing.JLabel();
        fig4 = new javax.swing.JLabel();
        pen4 = new javax.swing.JLabel();
        rawLabel = new javax.swing.JLabel();
        ddLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        figLabel = new javax.swing.JLabel();
        penLabel = new javax.swing.JLabel();
        judge1Label = new javax.swing.JLabel();
        judge2Label = new javax.swing.JLabel();
        judge3Label = new javax.swing.JLabel();
        judge4Label = new javax.swing.JLabel();
        judge5Label = new javax.swing.JLabel();
        penaltyLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        stationSelected.add(station1Button);
        station1Button.setText("Station 1 (A-1)");
        station1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                station1ButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(station1Button, gridBagConstraints);

        stationSelected.add(station2Button);
        station2Button.setText("Station 2 (A-2)");
        station2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                station2ButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(station2Button, gridBagConstraints);

        stationSelected.add(station3Button);
        station3Button.setText("Station 3 (B-1)");
        station3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                station3ButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(station3Button, gridBagConstraints);

        stationSelected.add(station4Button);
        station4Button.setText("Station 4 (B-2)");
        station4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                station4ButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        add(station4Button, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS1J1, gridBagConstraints);

        scoreS1J2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreS1J2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS1J2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS1J3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS1J4, gridBagConstraints);

        scoreS1J5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreS1J5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS1J5, gridBagConstraints);

        penalty2S1.setText("2 Point");
        penalty2S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penalty2S1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(penalty2S1, gridBagConstraints);

        penalty1S1.setText("1 Point");
        penalty1S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penalty1S1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        add(penalty1S1, gridBagConstraints);

        penaltyHS1.setText("1/2 Point");
        penaltyHS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penaltyHS1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        add(penaltyHS1, gridBagConstraints);

        raw1.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        add(raw1, gridBagConstraints);

        dd1.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        add(dd1, gridBagConstraints);

        total1.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 1;
        add(total1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 1;
        add(fig1, gridBagConstraints);

        pen1.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 1;
        add(pen1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS2J1, gridBagConstraints);

        scoreS2J2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreS2J2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS2J2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS2J3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS2J4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS2J5, gridBagConstraints);

        penalty2S2.setText("2 Point");
        penalty2S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penalty2S2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(penalty2S2, gridBagConstraints);

        penalty1S2.setText("1 Point");
        penalty1S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penalty1S2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        add(penalty1S2, gridBagConstraints);

        penaltyHS2.setText("1/2 Point");
        penaltyHS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penaltyHS2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        add(penaltyHS2, gridBagConstraints);

        raw2.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        add(raw2, gridBagConstraints);

        dd2.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        add(dd2, gridBagConstraints);

        total2.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 2;
        add(total2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 2;
        add(fig2, gridBagConstraints);

        pen2.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 2;
        add(pen2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS3J1, gridBagConstraints);

        scoreS3J2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreS3J2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS3J2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS3J3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS3J4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS3J5, gridBagConstraints);

        penalty2S3.setText("2 Point");
        penalty2S3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penalty2S3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(penalty2S3, gridBagConstraints);

        penalty1S3.setText("1 Point");
        penalty1S3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penalty1S3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        add(penalty1S3, gridBagConstraints);

        penaltyHS3.setText("1/2 Point");
        penaltyHS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penaltyHS3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        add(penaltyHS3, gridBagConstraints);

        raw3.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        add(raw3, gridBagConstraints);

        dd3.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 3;
        add(dd3, gridBagConstraints);

        total3.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 3;
        add(total3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 3;
        add(fig3, gridBagConstraints);

        pen3.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 3;
        add(pen3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS4J1, gridBagConstraints);

        scoreS4J2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreS4J2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS4J2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS4J3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS4J4, gridBagConstraints);

        scoreS4J5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreS4J5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(scoreS4J5, gridBagConstraints);

        penalty2S4.setText("2 Point");
        penalty2S4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penalty2S4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(penalty2S4, gridBagConstraints);

        penalty1S4.setText("1 Point");
        penalty1S4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penalty1S4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        add(penalty1S4, gridBagConstraints);

        penaltyHS4.setText("1/2 Point");
        penaltyHS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penaltyHS4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        add(penaltyHS4, gridBagConstraints);

        raw4.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 4;
        add(raw4, gridBagConstraints);

        dd4.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        add(dd4, gridBagConstraints);

        total4.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 4;
        add(total4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 4;
        add(fig4, gridBagConstraints);

        pen4.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 4;
        add(pen4, gridBagConstraints);

        rawLabel.setText("Raw");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        add(rawLabel, gridBagConstraints);

        ddLabel.setText("DD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        add(ddLabel, gridBagConstraints);

        totalLabel.setText("Total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        add(totalLabel, gridBagConstraints);

        figLabel.setText("Fig#");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        add(figLabel, gridBagConstraints);

        penLabel.setText("Pen.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        add(penLabel, gridBagConstraints);

        judge1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judge1Label.setText("Judge 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        add(judge1Label, gridBagConstraints);

        judge2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judge2Label.setText("Judge 2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        add(judge2Label, gridBagConstraints);

        judge3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judge3Label.setText("Judge 3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        add(judge3Label, gridBagConstraints);

        judge4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judge4Label.setText("Judge 4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        add(judge4Label, gridBagConstraints);

        judge5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judge5Label.setText("Judge 5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        add(judge5Label, gridBagConstraints);

        penaltyLabel.setText("Penalty");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(penaltyLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void scoreS1J2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreS1J2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_scoreS1J2ActionPerformed

    private void scoreS1J5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreS1J5ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_scoreS1J5ActionPerformed

    private void penalty2S3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penalty2S3ActionPerformed
        if(penalty2S3.isSelected()) {
            penalty1S3.setSelected(false);
            penaltyHS3.setSelected(false);
        }
}//GEN-LAST:event_penalty2S3ActionPerformed

    private void station1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_station1ButtonActionPerformed
        setEditableRow(1);
}//GEN-LAST:event_station1ButtonActionPerformed

    private void scoreS2J2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreS2J2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_scoreS2J2ActionPerformed

    private void penalty2S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penalty2S2ActionPerformed
        if(penalty2S2.isSelected()) {
            penalty1S2.setSelected(false);
            penaltyHS2.setSelected(false);
        }
}//GEN-LAST:event_penalty2S2ActionPerformed

    private void scoreS3J2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreS3J2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_scoreS3J2ActionPerformed

    private void penalty2S4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penalty2S4ActionPerformed
        if(penalty2S4.isSelected()) {
            penalty1S4.setSelected(false);
            penaltyHS4.setSelected(false);
        }
}//GEN-LAST:event_penalty2S4ActionPerformed

    private void scoreS4J2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreS4J2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_scoreS4J2ActionPerformed

    private void scoreS4J5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreS4J5ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_scoreS4J5ActionPerformed

    private void penalty2S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penalty2S1ActionPerformed
        if(penalty2S1.isSelected()) {
            penalty1S1.setSelected(false);
            penaltyHS1.setSelected(false);
        }
}//GEN-LAST:event_penalty2S1ActionPerformed

    private void station2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_station2ButtonActionPerformed
        setEditableRow(2);
    }//GEN-LAST:event_station2ButtonActionPerformed

    private void station3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_station3ButtonActionPerformed
        setEditableRow(3);
    }//GEN-LAST:event_station3ButtonActionPerformed

    private void station4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_station4ButtonActionPerformed
        setEditableRow(4);
    }//GEN-LAST:event_station4ButtonActionPerformed

    private void penalty1S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penalty1S1ActionPerformed
        if(penalty1S1.isSelected()) {
            penalty2S1.setSelected(false);
            penaltyHS1.setSelected(false);
        }
    }//GEN-LAST:event_penalty1S1ActionPerformed

    private void penaltyHS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penaltyHS1ActionPerformed
        if(penaltyHS1.isSelected()) {
            penalty2S1.setSelected(false);
            penalty1S1.setSelected(false);
        }
    }//GEN-LAST:event_penaltyHS1ActionPerformed

    private void penalty1S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penalty1S2ActionPerformed
        if(penalty1S2.isSelected()) {
            penalty2S2.setSelected(false);
            penaltyHS2.setSelected(false);
        }
    }//GEN-LAST:event_penalty1S2ActionPerformed

    private void penaltyHS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penaltyHS2ActionPerformed
        if(penaltyHS2.isSelected()) {
            penalty2S2.setSelected(false);
            penalty1S2.setSelected(false);
        }
    }//GEN-LAST:event_penaltyHS2ActionPerformed

    private void penalty1S3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penalty1S3ActionPerformed
        if(penalty1S3.isSelected()) {
            penalty2S3.setSelected(false);
            penaltyHS3.setSelected(false);
        }
    }//GEN-LAST:event_penalty1S3ActionPerformed

    private void penaltyHS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penaltyHS3ActionPerformed
        if(penaltyHS3.isSelected()) {
            penalty2S3.setSelected(false);
            penalty1S3.setSelected(false);
        }
    }//GEN-LAST:event_penaltyHS3ActionPerformed

    private void penalty1S4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penalty1S4ActionPerformed
        if(penalty1S4.isSelected()) {
            penalty2S4.setSelected(false);
            penaltyHS4.setSelected(false);
        }
    }//GEN-LAST:event_penalty1S4ActionPerformed

    private void penaltyHS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penaltyHS4ActionPerformed
        if(penaltyHS4.isSelected()) {
            penalty2S4.setSelected(false);
            penalty1S4.setSelected(false);
        }
    }//GEN-LAST:event_penaltyHS4ActionPerformed

    private void setEditableRow(int row) {
        boolean row1=(row==1);
        boolean row2=(row==2);
        boolean row3=(row==3);
        boolean row4=(row==4);
        scoreS1J1.setEditable(row1);
        scoreS1J2.setEditable(row1);
        scoreS1J3.setEditable(row1);
        scoreS1J4.setEditable(row1);
        scoreS1J5.setEditable(row1);
        penalty2S1.setEnabled(row1);
        penalty1S1.setEnabled(row1);
        penaltyHS1.setEnabled(row1);

        scoreS2J1.setEditable(row2);
        scoreS2J2.setEditable(row2);
        scoreS2J3.setEditable(row2);
        scoreS2J4.setEditable(row2);
        scoreS2J5.setEditable(row2);
        penalty2S2.setEnabled(row2);
        penalty1S2.setEnabled(row2);
        penaltyHS2.setEnabled(row2);

        scoreS3J1.setEditable(row3);
        scoreS3J2.setEditable(row3);
        scoreS3J3.setEditable(row3);
        scoreS3J4.setEditable(row3);
        scoreS3J5.setEditable(row3);
        penalty2S3.setEnabled(row3);
        penalty1S3.setEnabled(row3);
        penaltyHS3.setEnabled(row3);

        scoreS4J1.setEditable(row4);
        scoreS4J2.setEditable(row4);
        scoreS4J3.setEditable(row4);
        scoreS4J4.setEditable(row4);
        scoreS4J5.setEditable(row4);
        penalty2S4.setEnabled(row4);
        penalty1S4.setEnabled(row4);
        penaltyHS4.setEnabled(row4);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dd1;
    private javax.swing.JLabel dd2;
    private javax.swing.JLabel dd3;
    private javax.swing.JLabel dd4;
    private javax.swing.JLabel ddLabel;
    private javax.swing.JLabel fig1;
    private javax.swing.JLabel fig2;
    private javax.swing.JLabel fig3;
    private javax.swing.JLabel fig4;
    private javax.swing.JLabel figLabel;
    private javax.swing.JLabel judge1Label;
    private javax.swing.JLabel judge2Label;
    private javax.swing.JLabel judge3Label;
    private javax.swing.JLabel judge4Label;
    private javax.swing.JLabel judge5Label;
    private javax.swing.JLabel pen1;
    private javax.swing.JLabel pen2;
    private javax.swing.JLabel pen3;
    private javax.swing.JLabel pen4;
    private javax.swing.JLabel penLabel;
    private javax.swing.JCheckBox penalty1S1;
    private javax.swing.JCheckBox penalty1S2;
    private javax.swing.JCheckBox penalty1S3;
    private javax.swing.JCheckBox penalty1S4;
    private javax.swing.JCheckBox penalty2S1;
    private javax.swing.JCheckBox penalty2S2;
    private javax.swing.JCheckBox penalty2S3;
    private javax.swing.JCheckBox penalty2S4;
    private javax.swing.JCheckBox penaltyHS1;
    private javax.swing.JCheckBox penaltyHS2;
    private javax.swing.JCheckBox penaltyHS3;
    private javax.swing.JCheckBox penaltyHS4;
    private javax.swing.JLabel penaltyLabel;
    private javax.swing.JLabel raw1;
    private javax.swing.JLabel raw2;
    private javax.swing.JLabel raw3;
    private javax.swing.JLabel raw4;
    private javax.swing.JLabel rawLabel;
    private javax.swing.JTextField scoreS1J1;
    private javax.swing.JTextField scoreS1J2;
    private javax.swing.JTextField scoreS1J3;
    private javax.swing.JTextField scoreS1J4;
    private javax.swing.JTextField scoreS1J5;
    private javax.swing.JTextField scoreS2J1;
    private javax.swing.JTextField scoreS2J2;
    private javax.swing.JTextField scoreS2J3;
    private javax.swing.JTextField scoreS2J4;
    private javax.swing.JTextField scoreS2J5;
    private javax.swing.JTextField scoreS3J1;
    private javax.swing.JTextField scoreS3J2;
    private javax.swing.JTextField scoreS3J3;
    private javax.swing.JTextField scoreS3J4;
    private javax.swing.JTextField scoreS3J5;
    private javax.swing.JTextField scoreS4J1;
    private javax.swing.JTextField scoreS4J2;
    private javax.swing.JTextField scoreS4J3;
    private javax.swing.JTextField scoreS4J4;
    private javax.swing.JTextField scoreS4J5;
    private javax.swing.JRadioButton station1Button;
    private javax.swing.JRadioButton station2Button;
    private javax.swing.JRadioButton station3Button;
    private javax.swing.JRadioButton station4Button;
    private javax.swing.ButtonGroup stationSelected;
    private javax.swing.JLabel total1;
    private javax.swing.JLabel total2;
    private javax.swing.JLabel total3;
    private javax.swing.JLabel total4;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables

}
