/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MaintenancePanel.java
 *
 * Created on May 1, 2010, 7:34:07 PM
 */

package org.aquastarz.score.gui;

import java.awt.Cursor;
import java.beans.Beans;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.aquastarz.score.ScoreApp;
import org.aquastarz.score.config.Bootstrap;

/**
 *
 * @author shayne
 */
public class MaintenancePanel extends javax.swing.JPanel {

    /** Creates new form MaintenancePanel */
    public MaintenancePanel() {
        if (Beans.isDesignTime()) {
            initComponents();
        }
    }

    public void init() {
        if(maintenanceTab == null) initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maintenanceTab = new javax.swing.JTabbedPane();
        updateForm = new javax.swing.JPanel();
        load2009TestDataButton = new javax.swing.JButton();
        clearDBButton = new javax.swing.JButton();
        swimmerForm1 = new org.aquastarz.score.gui.dbform.SwimmerForm();
        teamForm1 = new org.aquastarz.score.gui.dbform.TeamForm();
        figureForm1 = new org.aquastarz.score.gui.dbform.FigureForm();
        levelForm1 = new org.aquastarz.score.gui.dbform.LevelForm();

        setLayout(new java.awt.CardLayout());

        maintenanceTab.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        load2009TestDataButton.setText("Load Data File");
        load2009TestDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load2009TestDataButtonActionPerformed(evt);
            }
        });

        clearDBButton.setText("Clear Database");
        clearDBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearDBButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateFormLayout = new javax.swing.GroupLayout(updateForm);
        updateForm.setLayout(updateFormLayout);
        updateFormLayout.setHorizontalGroup(
            updateFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateFormLayout.createSequentialGroup()
                        .addComponent(load2009TestDataButton)
                        .addContainerGap(757, Short.MAX_VALUE))
                    .addGroup(updateFormLayout.createSequentialGroup()
                        .addComponent(clearDBButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(766, 766, 766))))
        );
        updateFormLayout.setVerticalGroup(
            updateFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateFormLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(load2009TestDataButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                .addComponent(clearDBButton)
                .addContainerGap())
        );

        maintenanceTab.addTab("Update", updateForm);
        maintenanceTab.addTab("Swimmers", swimmerForm1);
        maintenanceTab.addTab("Teams", teamForm1);
        maintenanceTab.addTab("Figures", figureForm1);
        maintenanceTab.addTab("Levels", levelForm1);

        add(maintenanceTab, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void load2009TestDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load2009TestDataButtonActionPerformed
        Bootstrap.loadLeagueData();  //Just in case we cleared the db

        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Open SynchroScore data update");
        jfc.setFileFilter(new FileNameExtensionFilter("Zip file","zip"));
        int ret = jfc.showOpenDialog(this);
        if(ret == JFileChooser.APPROVE_OPTION) {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            Bootstrap.loadUpdateData(jfc.getSelectedFile());
            setCursor(Cursor.getDefaultCursor());
            JOptionPane.showMessageDialog(this, "Done.");
        }
}//GEN-LAST:event_load2009TestDataButtonActionPerformed

    private void clearDBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearDBButtonActionPerformed
        int ret = JOptionPane.showConfirmDialog(maintenanceTab, "Are you sure you want to wipe out all meets, swimmers, scores, etc?","Confirm Delete",JOptionPane.YES_NO_OPTION);
        if(ret!=JOptionPane.YES_OPTION) return;
        ret = JOptionPane.showConfirmDialog(maintenanceTab, "Really?  Everything?  There's no going back.  You may regret this.","Confirm Delete",JOptionPane.YES_NO_OPTION);
        if(ret!=JOptionPane.YES_OPTION) return;
        org.aquastarz.score.config.Bootstrap.clearDB(ScoreApp.getEntityManager());
        JOptionPane.showMessageDialog(this, "Done.");
}//GEN-LAST:event_clearDBButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearDBButton;
    private org.aquastarz.score.gui.dbform.FigureForm figureForm1;
    private org.aquastarz.score.gui.dbform.LevelForm levelForm1;
    private javax.swing.JButton load2009TestDataButton;
    private javax.swing.JTabbedPane maintenanceTab;
    private org.aquastarz.score.gui.dbform.SwimmerForm swimmerForm1;
    private org.aquastarz.score.gui.dbform.TeamForm teamForm1;
    private javax.swing.JPanel updateForm;
    // End of variables declaration//GEN-END:variables

}
