/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MaintenancePanel.java
 *
 * Created on May 1, 2010, 7:34:07 PM
 */

package org.aquastarz.score.gui;

import java.beans.Beans;
import javax.swing.JOptionPane;
import org.aquastarz.score.ScoreApp;
import org.aquastarz.score.config.Bootstrap;

/**
 *
 * @author shayne
 */
public class MaintenancePanel extends javax.swing.JPanel {

    /** Creates new form MaintenancePanel */
    public MaintenancePanel() {
        if (Beans.isDesignTime()) {
            initComponents();
        }
    }

    public void init() {
        if(maintenanceTab == null) initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maintenanceTab = new javax.swing.JTabbedPane();
        swimmerForm1 = new org.aquastarz.score.gui.dbform.SwimmerForm();
        teamForm1 = new org.aquastarz.score.gui.dbform.TeamForm();
        figureForm1 = new org.aquastarz.score.gui.dbform.FigureForm();
        levelForm1 = new org.aquastarz.score.gui.dbform.LevelForm();
        jPanel1 = new javax.swing.JPanel();
        load2009TestDataButton = new javax.swing.JButton();
        clearDBButton = new javax.swing.JButton();

        maintenanceTab.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        maintenanceTab.addTab("Swimmers", swimmerForm1);
        maintenanceTab.addTab("Teams", teamForm1);
        maintenanceTab.addTab("Figures", figureForm1);
        maintenanceTab.addTab("Levels", levelForm1);

        load2009TestDataButton.setText("Load 2009 Test Data");
        load2009TestDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load2009TestDataButtonActionPerformed(evt);
            }
        });

        clearDBButton.setText("Clear Database");
        clearDBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearDBButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(load2009TestDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearDBButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(739, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(clearDBButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(load2009TestDataButton)
                .addContainerGap(402, Short.MAX_VALUE))
        );

        maintenanceTab.addTab("Advanced", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 951, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(maintenanceTab, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(maintenanceTab, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void load2009TestDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load2009TestDataButtonActionPerformed
        Bootstrap.loadLeagueData();  //Just in case we cleared the db
        Bootstrap.load2009Season();
        JOptionPane.showMessageDialog(this, "Done.");
}//GEN-LAST:event_load2009TestDataButtonActionPerformed

    private void clearDBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearDBButtonActionPerformed
        org.aquastarz.score.config.Bootstrap.clearDB(ScoreApp.getEntityManager());
        JOptionPane.showMessageDialog(this, "Done.");
}//GEN-LAST:event_clearDBButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearDBButton;
    private org.aquastarz.score.gui.dbform.FigureForm figureForm1;
    private javax.swing.JPanel jPanel1;
    private org.aquastarz.score.gui.dbform.LevelForm levelForm1;
    private javax.swing.JButton load2009TestDataButton;
    private javax.swing.JTabbedPane maintenanceTab;
    private org.aquastarz.score.gui.dbform.SwimmerForm swimmerForm1;
    private org.aquastarz.score.gui.dbform.TeamForm teamForm1;
    // End of variables declaration//GEN-END:variables

}
