// <editor-fold defaultstate="collapsed" desc="GNU General Public License">
//
//   SynchroScore
//   Copyright (C) 2009 Shayne Hughes
//
//   This program is free software: you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation, either version 3 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.
//
//   You should have received a copy of the GNU General Public License
//   along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
// </editor-fold>
/*
 * MeetSelectionDialog.java
 *
 * Created on Apr 18, 2009, 2:19:57 PM
 */
package org.aquastarz.score.gui;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import org.aquastarz.score.domain.Meet;

/**
 *
 * @author Shayne Hughes <velocityfactor@gmail.com>
 */
public class MeetSelectionDialog extends javax.swing.JDialog {

    public boolean canceled = false;

    /** Creates new form MeetSelectionDialog */
    public MeetSelectionDialog(List<Meet> meets, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fillCombo(meetCombo, meets);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        newMeetButton = new javax.swing.JRadioButton();
        existingMeetButton = new javax.swing.JRadioButton();
        meetCombo = new javax.swing.JComboBox();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SynchroScore");
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        buttonGroup1.add(newMeetButton);
        newMeetButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newMeetButton.setText("New Meet");

        buttonGroup1.add(existingMeetButton);
        existingMeetButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        existingMeetButton.setText("Existing Meet");

        meetCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        meetCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        okButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newMeetButton)
                    .addComponent(existingMeetButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(meetCombo, 0, 256, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(newMeetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(existingMeetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        canceled = true;
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        canceled = true;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static Meet selectMeet(final List<Meet> meets) throws MeetSelectionCanceledException {
        MeetSelectionDialog dialog = new MeetSelectionDialog(meets, new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        if(dialog.canceled) {
            throw new MeetSelectionCanceledException();
        }
        return dialog.getSelectedMeet();
    }

    public static class MeetSelectionCanceledException extends Exception {

    }

    private Meet getSelectedMeet() {
        if (canceled) {
            return null;
        } else if (newMeetButton.isSelected()) {
            return null;
        } else if (existingMeetButton.isSelected()) {
            return (Meet) meetCombo.getSelectedItem();
        }

        return null;
    }

    private void fillCombo(JComboBox cb, List<Meet> meets) {
        DefaultComboBoxModel cbm = new DefaultComboBoxModel();
        for (Meet m : meets) {
            cbm.addElement(m);
        }
        cb.setModel(cbm);
        if (meets.size() == 0) {
            cb.setEnabled(false);
            existingMeetButton.setEnabled(false);
            newMeetButton.setSelected(true);
        } else {
            cb.setSelectedItem(meets.get(0));
//            if (isToday(meets.get(0).getMeetDate())) {
//                existingMeetButton.setSelected(true);
//            }
//            else {
//                newMeetButton.setSelected(true);
//            }
        }
    }

//    private boolean isToday(Date inp) {
//
//        Calendar cal1 = new GregorianCalendar();
//        Calendar cal2 = new GregorianCalendar();
//
//        cal1.setTime(new Date());
//        cal2.setTime(inp);
//
//        return ((cal1.get(Calendar.YEAR) == cal2.get(Calendar.YEAR)) &&
//                (cal1.get(Calendar.DAY_OF_YEAR) == cal2.get(Calendar.DAY_OF_YEAR)));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton existingMeetButton;
    private javax.swing.JComboBox meetCombo;
    private javax.swing.JRadioButton newMeetButton;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
