// <editor-fold defaultstate="collapsed" desc="GNU General Public License">
//
//   SynchroScore
//   Copyright (C) 2009 Shayne Hughes
//
//   This program is free software: you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation, either version 3 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.
//
//   You should have received a copy of the GNU General Public License
//   along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
// </editor-fold>
package org.aquastarz.score.gui;

import java.awt.Component;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.ListSelectionModel;
import org.aquastarz.score.ScoreApp;
import org.aquastarz.score.controller.ScoreController;
import org.aquastarz.score.domain.Figure;
import org.aquastarz.score.domain.Meet;
import org.aquastarz.score.domain.Team;

public class MeetSetupPanel extends javax.swing.JPanel {

    ScoreController controller;

    /** Creates new form MeetSetupPanel */
    public MeetSetupPanel() {
        controller=ScoreController.getInstance();
        initComponents();
        fillLists();
    }

    private void fillLists() {
        if (!java.beans.Beans.isDesignTime()) {
            javax.persistence.EntityManager entityManager = ScoreApp.getEntityManager();

            //Get the list of Teams
            javax.persistence.Query query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM Team t order by t.name");
            Collection<Team> data = query.getResultList();

            //Fill a Vector for the JList and a ComboBoxModel for the ComboBox
            DefaultComboBoxModel cbm=new DefaultComboBoxModel();
            Vector<CheckListItem<Team>> v = new Vector<CheckListItem<Team>>();
            for (Team t : data) {
                v.add(new CheckListItem(t, t.getName()));
                cbm.addElement(t);
            }

            //Set up the JList as a list of checkboxes
            opponents.setListData(v);
            CheckListCellRenderer renderer = new CheckListCellRenderer();
            opponents.setCellRenderer(renderer);
            opponents.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            CheckListener lst = new CheckListener(opponents);
            opponents.addMouseListener(lst);
            opponents.addKeyListener(lst);

            //Set ComboBox model
            homeTeam.setModel(cbm);

        }


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        synchroPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("synchroPU").createEntityManager();
        figureQuery = java.beans.Beans.isDesignTime() ? null : synchroPUEntityManager.createQuery("SELECT f FROM Figure f");
        figureList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : figureQuery.getResultList();
        teamQuery = java.beans.Beans.isDesignTime() ? null : synchroPUEntityManager.createQuery("select t from Team t");
        teamList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : teamQuery.getResultList();
        meetTypeButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        meetName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        meetDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        noviceFigNum1 = new javax.swing.JTextField();
        noviceDD1 = new javax.swing.JTextField();
        eightAndUnder1 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        noviceFigNum2 = new javax.swing.JTextField();
        noviceDD2 = new javax.swing.JTextField();
        eightAndUnder2 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        noviceFigNum3 = new javax.swing.JTextField();
        noviceDD3 = new javax.swing.JTextField();
        eightAndUnder3 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        noviceFigNum4 = new javax.swing.JTextField();
        noviceDD4 = new javax.swing.JTextField();
        eightAndUnder4 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        intFigNum1 = new javax.swing.JTextField();
        intFigNum2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        intDD1 = new javax.swing.JTextField();
        intDD2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        intFigNum4 = new javax.swing.JTextField();
        intDD4 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        intFigNum3 = new javax.swing.JTextField();
        intDD3 = new javax.swing.JTextField();
        homeTeam = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        opponents = new javax.swing.JList();
        saveButton = new javax.swing.JButton();
        noviceFigName1 = new javax.swing.JComboBox();
        noviceFigName2 = new javax.swing.JComboBox();
        noviceFigName3 = new javax.swing.JComboBox();
        noviceFigName4 = new javax.swing.JComboBox();
        intFigName1 = new javax.swing.JComboBox();
        intFigName2 = new javax.swing.JComboBox();
        intFigName3 = new javax.swing.JComboBox();
        intFigName4 = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        regularMeetButton = new javax.swing.JRadioButton();
        champsButton = new javax.swing.JRadioButton();

        jLabel1.setText("Title for Meet Report");

        meetName.setText("Mock Meet");

        jLabel2.setText("Meet Date");

        meetDate.setMaximumSize(new java.awt.Dimension(114, 20));
        meetDate.setMinimumSize(new java.awt.Dimension(114, 20));

        jLabel3.setText("Novice Figures");

        jLabel4.setText("Station 1 (A-1)");

        jLabel5.setText("Figure Description");

        jLabel6.setText("DD");

        jLabel7.setText("Fig. #");

        jLabel8.setText("8 and Under");

        noviceFigNum1.setFocusable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, noviceFigName1, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.number}"), noviceFigNum1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        noviceDD1.setFocusable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, noviceFigName1, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.degreeOfDifficulty}"), noviceDD1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel9.setText("Station 2 (A-2)");

        noviceFigNum2.setFocusable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, noviceFigName2, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.number}"), noviceFigNum2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        noviceDD2.setFocusable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, noviceFigName2, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.degreeOfDifficulty}"), noviceDD2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel10.setText("Station 3 (B-1)");

        noviceFigNum3.setFocusable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, noviceFigName3, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.number}"), noviceFigNum3, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        noviceDD3.setFocusable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, noviceFigName3, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.degreeOfDifficulty}"), noviceDD3, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel11.setText("Station 4 (B-2)");

        noviceFigNum4.setFocusable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, noviceFigName4, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.number}"), noviceFigNum4, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        noviceDD4.setFocusable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, noviceFigName4, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.degreeOfDifficulty}"), noviceDD4, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel12.setText("Station 1 (A-1)");

        jLabel13.setText("Station 2 (A-2)");

        jLabel14.setText("Fig. #");

        intFigNum1.setFocusable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, intFigName1, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.number}"), intFigNum1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        intFigNum2.setFocusable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, intFigName2, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.number}"), intFigNum2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel15.setText("DD");

        intDD1.setFocusable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, intFigName1, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.degreeOfDifficulty}"), intDD1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        intDD2.setFocusable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, intFigName2, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.degreeOfDifficulty}"), intDD2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel16.setText("Figure Description");

        jLabel17.setText("Intermediate Figures");

        jLabel19.setText("Station 4 (B-2)");

        intFigNum4.setFocusable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, intFigName4, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.number}"), intFigNum4, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        intDD4.setFocusable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, intFigName4, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.degreeOfDifficulty}"), intDD4, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel20.setText("Station 3 (B-1)");

        intFigNum3.setFocusable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, intFigName3, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.number}"), intFigNum3, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        intDD3.setFocusable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, intFigName3, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.degreeOfDifficulty}"), intDD3, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        homeTeam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel18.setText("Home Team");

        jLabel21.setText("Opponents");

        jScrollPane1.setViewportView(opponents);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        noviceFigName1.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Figure) {
                    Figure mec = (Figure)value;
                    setText(mec.getName());
                }
                return this;
            }
        });

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, figureList, noviceFigName1);
        bindingGroup.addBinding(jComboBoxBinding);

        noviceFigName2.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Figure) {
                    Figure mec = (Figure)value;
                    setText(mec.getName());
                }
                return this;
            }
        });

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, figureList, noviceFigName2);
        bindingGroup.addBinding(jComboBoxBinding);

        noviceFigName3.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Figure) {
                    Figure mec = (Figure)value;
                    setText(mec.getName());
                }
                return this;
            }
        });

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, figureList, noviceFigName3);
        bindingGroup.addBinding(jComboBoxBinding);

        noviceFigName4.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Figure) {
                    Figure mec = (Figure)value;
                    setText(mec.getName());
                }
                return this;
            }
        });

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, figureList, noviceFigName4);
        bindingGroup.addBinding(jComboBoxBinding);

        intFigName1.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Figure) {
                    Figure mec = (Figure)value;
                    setText(mec.getName());
                }
                return this;
            }
        });

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, figureList, intFigName1);
        bindingGroup.addBinding(jComboBoxBinding);

        intFigName2.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Figure) {
                    Figure mec = (Figure)value;
                    setText(mec.getName());
                }
                return this;
            }
        });

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, figureList, intFigName2);
        bindingGroup.addBinding(jComboBoxBinding);

        intFigName3.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Figure) {
                    Figure mec = (Figure)value;
                    setText(mec.getName());
                }
                return this;
            }
        });

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, figureList, intFigName3);
        bindingGroup.addBinding(jComboBoxBinding);

        intFigName4.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Figure) {
                    Figure mec = (Figure)value;
                    setText(mec.getName());
                }
                return this;
            }
        });

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, figureList, intFigName4);
        bindingGroup.addBinding(jComboBoxBinding);

        jLabel22.setText("Meet type:");

        meetTypeButtonGroup.add(regularMeetButton);
        regularMeetButton.setSelected(true);
        regularMeetButton.setText("Regular");

        meetTypeButtonGroup.add(champsButton);
        champsButton.setText("Championship");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveButton)
                .addContainerGap(882, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(meetName, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(noviceFigNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noviceFigNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noviceFigNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noviceFigNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(intFigNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intFigNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intFigNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intFigNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(noviceDD1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noviceDD2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noviceDD4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noviceDD3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(intDD1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intDD2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intDD4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intDD3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(intFigName4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(intFigName3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(intFigName2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(intFigName1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(noviceFigName1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noviceFigName4, 0, 186, Short.MAX_VALUE)
                            .addComponent(noviceFigName3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noviceFigName2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(eightAndUnder1)
                            .addComponent(eightAndUnder2)
                            .addComponent(eightAndUnder4)
                            .addComponent(eightAndUnder3)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(regularMeetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(champsButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(meetDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel21)
                                    .addComponent(homeTeam, 0, 215, Short.MAX_VALUE)
                                    .addComponent(jLabel18)))
                            .addGap(156, 156, 156))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(321, 321, 321)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(meetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(meetDate, 0, 0, Short.MAX_VALUE)))
                    .addComponent(jLabel2))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(regularMeetButton)
                            .addComponent(champsButton))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(noviceFigNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(noviceDD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(noviceFigName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eightAndUnder1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(noviceFigNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(noviceDD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(noviceFigName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eightAndUnder2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(noviceFigNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(noviceDD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(noviceFigName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eightAndUnder3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(noviceFigNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(noviceDD4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(noviceFigName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eightAndUnder4))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(intFigNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intDD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intFigName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(intFigNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intDD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intFigName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(intFigNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intDD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intFigName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(intFigNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intDD4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intFigName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        //Create a Meet object and pass it to the controller
        Meet meet = new Meet();
        meet.setName(meetName.getText());
        meet.setDate(meetDate.getDate());
        meet.setType(champsButton.isSelected()?'C':'R');
        meet.setHomeTeam((Team)homeTeam.getSelectedItem());
        List<Team> op = new ArrayList<Team>();
        for(Object obj:opponents.getSelectedValues()) {
            CheckListItem cli = (CheckListItem) obj;
            op.add((Team)cli.getItem());
        }
        meet.setOpponents(op);
        meet.setNov1Figure((Figure)noviceFigName1.getSelectedItem());
        meet.setNov2Figure((Figure)noviceFigName2.getSelectedItem());
        meet.setNov3Figure((Figure)noviceFigName3.getSelectedItem());
        meet.setNov4Figure((Figure)noviceFigName4.getSelectedItem());
        meet.setInt1Figure((Figure)intFigName1.getSelectedItem());
        meet.setInt2Figure((Figure)intFigName2.getSelectedItem());
        meet.setInt3Figure((Figure)intFigName3.getSelectedItem());
        meet.setInt4Figure((Figure)intFigName4.getSelectedItem());
        meet.setEu1Figure(null);
        meet.setEu2Figure(null);
        if(eightAndUnder1.isSelected()) {
            if(meet.getEu1Figure()==null) {
                meet.setEu1Figure(meet.getNov1Figure());
            }
            else {
                meet.setEu2Figure(meet.getNov1Figure());
            }
        }
        if(eightAndUnder2.isSelected()) {
            if(meet.getEu1Figure()==null) {
                meet.setEu1Figure(meet.getNov2Figure());
            }
            else {
                meet.setEu2Figure(meet.getNov2Figure());
            }
        }
        if(eightAndUnder3.isSelected()) {
            if(meet.getEu1Figure()==null) {
                meet.setEu1Figure(meet.getNov3Figure());
            }
            else {
                meet.setEu2Figure(meet.getNov3Figure());
            }
        }
        if(eightAndUnder4.isSelected()) {
            if(meet.getEu1Figure()==null) {
                meet.setEu1Figure(meet.getNov4Figure());
            }
            else {
                meet.setEu2Figure(meet.getNov4Figure());
            }
        }
        controller.meetSetupSaved(meet);
    }//GEN-LAST:event_saveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton champsButton;
    private javax.swing.JCheckBox eightAndUnder1;
    private javax.swing.JCheckBox eightAndUnder2;
    private javax.swing.JCheckBox eightAndUnder3;
    private javax.swing.JCheckBox eightAndUnder4;
    private java.util.List<org.aquastarz.score.domain.Figure> figureList;
    private javax.persistence.Query figureQuery;
    private javax.swing.JComboBox homeTeam;
    private javax.swing.JTextField intDD1;
    private javax.swing.JTextField intDD2;
    private javax.swing.JTextField intDD3;
    private javax.swing.JTextField intDD4;
    private javax.swing.JComboBox intFigName1;
    private javax.swing.JComboBox intFigName2;
    private javax.swing.JComboBox intFigName3;
    private javax.swing.JComboBox intFigName4;
    private javax.swing.JTextField intFigNum1;
    private javax.swing.JTextField intFigNum2;
    private javax.swing.JTextField intFigNum3;
    private javax.swing.JTextField intFigNum4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker meetDate;
    private javax.swing.JTextField meetName;
    private javax.swing.ButtonGroup meetTypeButtonGroup;
    private javax.swing.JTextField noviceDD1;
    private javax.swing.JTextField noviceDD2;
    private javax.swing.JTextField noviceDD3;
    private javax.swing.JTextField noviceDD4;
    private javax.swing.JComboBox noviceFigName1;
    private javax.swing.JComboBox noviceFigName2;
    private javax.swing.JComboBox noviceFigName3;
    private javax.swing.JComboBox noviceFigName4;
    private javax.swing.JTextField noviceFigNum1;
    private javax.swing.JTextField noviceFigNum2;
    private javax.swing.JTextField noviceFigNum3;
    private javax.swing.JTextField noviceFigNum4;
    private javax.swing.JList opponents;
    private javax.swing.JRadioButton regularMeetButton;
    private javax.swing.JButton saveButton;
    private javax.persistence.EntityManager synchroPUEntityManager;
    private java.util.List teamList;
    private javax.persistence.Query teamQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
