// <editor-fold defaultstate="collapsed" desc="GNU General Public License">
//
//   SynchroScore
//   Copyright (C) 2009 Shayne Hughes
//
//   This program is free software: you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation, either version 3 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.
//
//   You should have received a copy of the GNU General Public License
//   along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
// </editor-fold>
package org.aquastarz.score.gui;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Vector;
import javax.swing.ListSelectionModel;
import org.aquastarz.score.domain.Swimmer;
import org.aquastarz.score.domain.Team;

public class SwimmerSelectionPanel extends javax.swing.JPanel {

    /** Creates new form SwimmerSelectionPanel */
    public SwimmerSelectionPanel(Team team, List<Swimmer> roster, Collection<Swimmer> participatingSwimmers) {
        initComponents();

        teamNameLabel.setText("Participating swimmers for "+team.getName()+":");

        Vector<CheckListItem<Swimmer>> checkListItems = new Vector<CheckListItem<Swimmer>>();
        for (Swimmer swimmer : roster) {
            CheckListItem<Swimmer> item = new CheckListItem<Swimmer>(swimmer, swimmer.toString());
            if(participatingSwimmers==null || participatingSwimmers.contains(swimmer)) item.setSelected(true);
            checkListItems.add(item);
        }
        swimmerList.setListData(checkListItems);

        CheckListCellRenderer renderer = new CheckListCellRenderer();
        swimmerList.setCellRenderer(renderer);
        swimmerList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        CheckListener lst = new CheckListener(swimmerList);
        swimmerList.addMouseListener(lst);
        swimmerList.addKeyListener(lst);
    }

    public Collection<Swimmer> getSelectedSwimmers() {
        ArrayList<Swimmer> swimmers=new ArrayList<Swimmer>();
        for(int i=0;i<swimmerList.getModel().getSize();i++) {
            CheckListItem<Swimmer> item = (CheckListItem<Swimmer>)swimmerList.getModel().getElementAt(i);
            if(item.isSelected()) swimmers.add(item.getItem());
        }
        return swimmers;
    }

    private void setAll(boolean selected) {
        for(int i=0;i<swimmerList.getModel().getSize();i++) {
            CheckListItem<Swimmer> item = (CheckListItem<Swimmer>)swimmerList.getModel().getElementAt(i);
            item.setSelected(selected);
        }
        swimmerList.invalidate();
        swimmerList.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teamNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        swimmerList = new javax.swing.JList();
        selectAllButton = new javax.swing.JButton();
        selectNoneButton = new javax.swing.JButton();

        teamNameLabel.setText("Swimmers for Team Name");

        swimmerList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(swimmerList);

        selectAllButton.setText("Select All");
        selectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllButtonActionPerformed(evt);
            }
        });

        selectNoneButton.setText("Select None");
        selectNoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectNoneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(teamNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(selectAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectNoneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teamNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectAllButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectNoneButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllButtonActionPerformed
        setAll(true);
    }//GEN-LAST:event_selectAllButtonActionPerformed

    private void selectNoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectNoneButtonActionPerformed
        setAll(false);
    }//GEN-LAST:event_selectNoneButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton selectAllButton;
    private javax.swing.JButton selectNoneButton;
    private javax.swing.JList swimmerList;
    private javax.swing.JLabel teamNameLabel;
    // End of variables declaration//GEN-END:variables

}
