// <editor-fold defaultstate="collapsed" desc="GNU General Public License">
//
//   SynchroScore
//   Copyright (C) 2009 Shayne Hughes
//
//   This program is free software: you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation, either version 3 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.
//
//   You should have received a copy of the GNU General Public License
//   along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
// </editor-fold>
package org.aquastarz.score.gui;

public class SwimmerSearchPanel extends javax.swing.JPanel {

    /** Creates new form SwimmerSearchPanel */
    public SwimmerSearchPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        meetLabel = new javax.swing.JLabel();
        meetSwimmerNumber = new javax.swing.JTextField();
        leagueLabel = new javax.swing.JLabel();
        leagueSwimmerNumber = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        swimmerName = new javax.swing.JLabel();
        teamLabel = new javax.swing.JLabel();
        swimmerTeam = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        swimmerLevel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        meetLabel.setText("Meet #:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(meetLabel, gridBagConstraints);

        meetSwimmerNumber.setText("99");
        meetSwimmerNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meetSwimmerNumberActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(meetSwimmerNumber, gridBagConstraints);

        leagueLabel.setText("League #:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(leagueLabel, gridBagConstraints);

        leagueSwimmerNumber.setBackground(new java.awt.Color(255, 255, 255));
        leagueSwimmerNumber.setText("999");
        leagueSwimmerNumber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        leagueSwimmerNumber.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        add(leagueSwimmerNumber, gridBagConstraints);

        nameLabel.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        add(nameLabel, gridBagConstraints);

        swimmerName.setBackground(java.awt.SystemColor.text);
        swimmerName.setText("Swimmer, Suzie");
        swimmerName.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        add(swimmerName, gridBagConstraints);

        teamLabel.setText("Team:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(teamLabel, gridBagConstraints);

        swimmerTeam.setBackground(java.awt.SystemColor.text);
        swimmerTeam.setText("ABC");
        swimmerTeam.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        add(swimmerTeam, gridBagConstraints);

        levelLabel.setText("Level:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(levelLabel, gridBagConstraints);

        swimmerLevel.setBackground(java.awt.SystemColor.text);
        swimmerLevel.setText("Novice 9-10");
        swimmerLevel.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        add(swimmerLevel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void meetSwimmerNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meetSwimmerNumberActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_meetSwimmerNumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel leagueLabel;
    private javax.swing.JLabel leagueSwimmerNumber;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel meetLabel;
    private javax.swing.JTextField meetSwimmerNumber;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel swimmerLevel;
    private javax.swing.JLabel swimmerName;
    private javax.swing.JLabel swimmerTeam;
    private javax.swing.JLabel teamLabel;
    // End of variables declaration//GEN-END:variables

}
